export default styles = ({ colors, fontSizes }) => ({
  container: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.secondary,
  },
  heading: {
    margin: 20,
    marginTop: 40,
    color: colors.text,
    fontSize: fontSizes.large,
    fontFamily: 'HalkenRegular',
    textAlign: 'center',
  },
  lower: {
    position: 'absolute',
    top: 0,
    left: '-130%',
    width: '250%',
    height: '80%',
    backgroundColor: colors.primary,
    borderBottomRightRadius: 400,
  },
  message: {
    margin: 20,
    marginTop: 40,
    color: colors.text,
    fontSize: fontSizes.medium,
    fontFamily: 'Futura-Medium',
    lineHeight: 24,
  },
  videoCredit: {
    margin: 20,
    marginBottom: 40,
    color: colors.text,
    fontSize: fontSizes.medium,
    fontFamily: 'Futura-Medium',
    lineHeight: 24,
    textAlign: 'center',
  },
  videoLink: {
    color: colors.text,
    fontSize: fontSizes.medium,
    fontFamily: 'Futura-Medium',
    lineHeight: 24,
    textDecorationLine: 'underline',
    textDecorationStyle: 'solid',
  },
});
